version: '3.8'

volumes:
  db-data:
    driver: local
  upload-data:
    driver: local

networks:
  homechief:
    driver: bridge

services:
  homechief2:
    image: java2048/homechief:latest
    container_name: homechief_name
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      SPRING_DATASOURCE_URL: jdbc:postgresql://myjavapost-service:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - homechief
    ports:
      - '8090:8090'
    volumes:
      - ./uploads:/home/admins/StartUps/HomeChief/backend/HomeChiefBack/uploads
