version: '3.8'

volumes:
  db-data:
    driver: local
  upload-data:
    driver: local

networks:
  homechief:
    driver: bridge

services:
  postgres:
    image: postgres:15.1-alpine
    container_name: homechief-database-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - homechief

  homechief2:
    image: java2048/homechief:latest
    container_name: homechief_name
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - homechief
    ports:
      - '8090:8090'
    volumes:
      - ./uploads:/home/admins/StartUps/HomeChief/backend/HomeChiefBack/uploads
